{  
  "code":"0",
  "msg":"",
  "data":[  
     {  
        "name":"用户权限管理",
        "title":null,
        "jump":null,
        "icon":"fa fa-laptop",
        "list":[  
           {  
              "name":"角色分配",
              "title":null,
              "jump":"/UserRole/Index",
              "icon":"",
              "list":null
           },
           {  
              "name":"菜单权限",
              "title":null,
              "jump":"/RoleRight/Index",
              "icon":"",
              "list":null
           },
           {  
              "name":"菜单管理",
              "title":null,
              "jump":"/Right/Index",
              "icon":"",
              "list":null
           },
           {  
              "name":"角色管理",
              "title":null,
              "jump":"/Role/Index",
              "icon":"",
              "list":null
           },
           {  
              "name":"用户管理",
              "title":null,
              "jump":"/User/Index",
              "icon":"",
              "list":null
           }
        ]
     }
  ]
}